---
- name: This playbook list the version of the setup package
  hosts: ansible-c-1
  tasks:
    - name: Gather package information
      package_facts:
        manager: auto
    - name: Displaying the setup package
      debug:
        msg: The setup package version is {{ packages['setup'] [0].version }}
...