---
- name: This playbook installs packages
  hosts: ansible-c-1
  tasks:
  - name: Installing both bind and evolution packages
    yum:
      name: "{{ packages }}"
      state: latest
    register: results

  - name: Displays entire task output
    debug:
      var: results

  - name: Displays the name of the installed packages
    debug:
      msg: The name of the installed packages are called {{ results['results'] }}
...