---
- name: Play 1 - Copy a file from local to ansible-c-1
  hosts: ansible-c-1
  tasks:
  - name: Copy /etc/issue from local to the host stated
    copy:
      src: /etc/issue
      dest: /etc/issue
      owner: user4000
      group: cloudadmins
      mode: 444

- name: Play 2 - Changing the timezone
  hosts: linux
  tasks:
  - name: Set timezone to America/Edmonton
    timezone: 
      name: America/Edmonton
      
- name: Play 3 - Create a group and user
  hosts: ansible-c-2
  tasks:
  - name: Create a group
    group:
      name: devops
      state: present
  - name: Create a user
    user:
      name: devops1
      uid: 2500
      groups: devops
      append: yes
      state: present
...