---
- name: This play checks which nodes have user1 or not
  hosts: linux

  tasks: 
    - name: capture user information
      command: cat /etc/passwd
      register: users

    - name: show which node have user1
      debug: 
        msg: "This node has the user1"
      when: users.stdout.find('user1') != -1        
...