---
# tasks file for profile_mgmt
- name: make changes to /etc/profile file
  blockinfile:
    path: "{{abspath}}"
    insertafter: EOF
    backup: yes
    state: present
    block: |
      export TMOUT=900

- name: set unmask to 0077
  lineinfile:
    path: "{{abspath}}"
    regex: "^umask"
    line: "umask 0077"
    state: present

- name: run the task below if either of the above fails
  lineinfile:
    path: ~/.bash_profile
    regex: "^umask"
    line: "umask 0066"
    state: present     

- name: this tasks will run always
  debug:
    msg: Playbook execution completed

... 